- name: make skel bin dir
  become: yes
  file: path=/etc/skel/bin state=directory mode=0755

- name: modify path to contain HOME/bin
  become: yes
  lineinfile: dest=/etc/skel/.bashrc line='export PATH="$HOME/bin:$PATH"'

- name: modify ld library path in skel
  become: yes
  lineinfile: dest=/etc/skel/.bashrc line='export LD_LIBRARY_PATH="/usr/lib:/usr/lib64:/usr/local/lib:/usr/local/lib64:$LD_LIBRARY_PATH"'

- name: allow mosh
  become: yes
  lineinfile: "dest=/etc/sysconfig/iptables line='-A INPUT -p udp -m multiport --dports 60000:61000 -j ACCEPT' insertafter='ESTABLISHED'"
  register: allowmosh

- name: restart iptables
  become: yes
  service: name=iptables enabled=yes state=restarted
  when: allowmosh.changed

- name: ensure docker running
  become: yes
  service: name=docker enabled=yes state=started

- name: install ansible2
  become: yes
  pip: name=ansible executable=/usr/bin/pip2

- name: install docker-py
  become: yes
  pip: name=docker-py executable=/usr/bin/pip2

- group: name=docker state=present
  become: yes

- user: name={{ansible_env.USER}} groups=docker append=yes
  become: yes

#- name: disable intel cpu governor
  #become: yes
  #lineinfile: "dest=/etc/default/grub line='GRUB_CMDLINE_LINUX=\"rd.lvm.lv=fedorasys/root rd.lvm.lv=fedorasys/swap nodmraid rhgb quiet rd.shell=0 intel_pstate=disable\"' regexp='^GRUB_CMDLINE_LINUX'"
  #register: intelgovernor

#- name: reconfigure grub
  #become: yes
  #command: "grub2-mkconfig -o /boot/grub2/grub.cfg"
  #when: intelgovernor.changed

#- include: ../../common/tasks/reboot.yml
  #when: intelgovernor.changed

- name: enable performance governor
  become: yes
  command: "cpupower frequency-set -g performance"

- name: set selinux permissive
  become: yes
  command: "setenforce Permissive"
