- name: clone folly repository
  git: repo=https://github.com/facebook/folly.git dest={{ ansible_env.HOME }}/libsrc/folly depth=1 version=v0.35.0 update=no

- name: change folly build
  lineinfile: "dest={{ ansible_env.HOME }}/libsrc/folly/folly/m4/ax_boost_context.m4 regexp='fcontext_t' line='                [[boost::context::fcontext_t fc = boost::context::make_fcontext(0, 0, 0);]])],'"

- name: build folly
  shell: cd libsrc/folly/folly && autoreconf -ivf && ./configure && make creates={{ ansible_env.HOME }}/libsrc/folly/folly/.libs/libfolly.so

- name: install folly
  become: yes
  shell: cd libsrc/folly/folly && make install && ldconfig creates=/usr/local/lib/libfolly.so

- name: clone fbthrift repository
  git: repo=https://github.com/facebook/fbthrift.git dest={{ ansible_env.HOME }}/libsrc/fbthrift depth=1 version=v0.24.0 update=no

- name: build fbthrift
  shell: cd libsrc/fbthrift/thrift && autoreconf -ivf && ./configure && make creates={{ ansible_env.HOME }}/libsrc/fbthrift/thrift/lib/cpp2/.libs/libthriftcpp2.so

- name: install fbthrift
  become: yes
  shell: cd libsrc/fbthrift/thrift && make install creates=/usr/local/lib/libthriftcpp2.so

- name: clone thpp repository
  git: repo=https://github.com/facebook/thpp dest={{ ansible_env.HOME }}/libsrc/thpp update=no

- name: change thpp build
  lineinfile: "dest={{ ansible_env.HOME }}/libsrc/thpp/thpp/build.sh line='sudo make install' state=absent"

- name: build thpp
  shell: "{{ torch_source_cmd }} && cd libsrc/thpp/thpp && ./build.sh creates={{ ansible_env.HOME }}/libsrc/thpp/thpp/build/libthpp.so"

- name: install thpp
  become: yes
  shell: cd libsrc/thpp/thpp/build && make install creates=/usr/local/lib/libthpp.so

- name: clone fblualib repository
  git: repo=https://github.com/soumith/fblualib dest={{ ansible_env.HOME }}/libsrc/fblualib update=no

- name: build fblualib
  shell: "{{ torch_source_cmd }} && cd libsrc/fblualib/fblualib && mkdir -p build && cd build && cmake .. && make creates={{ ansible_env.HOME }}/libsrc/fblualib/fblualib/build/libfblualib.so"

- name: install fblualib
  become: yes
  shell: cd libsrc/fblualib/fblualib/build && make install creates=/usr/local/lib/libfblualib.so

- name: install ansible2
  become: yes
  pip: name=ansible executable=/usr/bin/pip2

- name: clone nccl
  git: repo=https://github.com/NVIDIA/nccl.git dest={{ ansible_env.HOME }}/libsrc/nccl

- name: build nccl
  shell: cd libsrc/nccl && make creates={{ ansible_env.HOME }}/libsrc/nccl/build/lib/libnccl.so
  environment: "{{ cuda75_env }}"

- name: install nccl
  become: yes
  shell: cd libsrc/nccl && make install creates=/usr/local/lib/libnccl.so
  environment: "{{ cuda75_env }}"
