- name: download atlas
  get_url: url='http://downloads.sourceforge.net/project/math-atlas/Stable/3.10.2/atlas3.10.2.tar.bz2' dest={{ ansible_env.HOME }}/libsrc/atlas.tar.bz2

- name: download lapack
  get_url: url='http://www.netlib.org/lapack/lapack-3.6.1.tgz' dest={{ ansible_env.HOME }}/libsrc/lapack.tgz

- name: unpack atlas
  unarchive: src={{ansible_env.HOME}}/libsrc/atlas.tar.bz2 copy=no dest={{ansible_env.HOME}}/libsrc creates={{ansible_env.HOME}}/libsrc/ATLAS/configure

- name: build atlas
  become: yes
  shell: "cd libsrc/ATLAS ; mkdir -p build ; cd build ; ../configure --with-netlib-lapack-tarfile=$HOME/libsrc/lapack.tgz && make && make install" #TODO: creates

- name: download fftw
  get_url: url='http://www.fftw.org/fftw-3.3.4.tar.gz' dest={{ansible_env.HOME}}/libsrc/fftw.tar.gz

- name: unpack fftw
  unarchive: src={{ansible_env.HOME}}/libsrc/fftw.tar.gz copy=no dest={{ansible_env.HOME}}/libsrc creates=libsrc/fftw-3.3.4/configure

- name: build fftw
  become: yes
  shell: "cd libsrc/fftw-3.3.4 ; ./configure && make && make install" #TODO: creates
