#- hosts: bpu

  #remote_user: root

  #vars:
    #- username: ykilcher
    #- uid: 123937
    #- groupname: hofmann
    #- gid: 10275

  #tasks:
    #- name: create user group
      #group: name={{ groupname }} gid={{ gid }}

    #- name: create remote non-root user
      #user: name={{ username }} uid={{ uid }} group={{ groupname }} home=/local/home/{{ username }}
      #register: createuser

    #- name: set password
      #shell: "date +%s | sha256sum | base64 | head -c 32 | passwd --stdin {{ username }}"
      #when: createuser.changed

    #- name: add user to sudoers
      #lineinfile: "dest=/etc/sudoers state=present regexp='^{{ username }}' line='{{ username }} ALL=(ALL) NOPASSWD: ALL'"

    #- name: add public key
      #authorized_key: user={{ username }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}" path="/local/home/{{ username }}/.ssh/authorized_keys"


- hosts: bpu

  vars:
    torch_source_cmd: ". $HOME/torch/install/bin/torch-activate"
    cuda75_env:
      CUDA_ROOT: /usr/local/cuda-7.5
      CUDA_HOME: /usr/local/cuda-7.5
      CFLAGS: -I/usr/local/cuda-7.5/include 
      LDFLAGS: -L/usr/local/cuda-7.5/lib64 
      PATH: "/usr/local/cuda-7.5/bin:{{ ansible_env.PATH }}"
      LD_LIBRARY_PATH: "/usr/local/cuda-7.5/lib64:{{ ansible_env.LD_LIBRARY_PATH | default('') }}"

  roles:
      - common
      - dnf-basics-f22
      - zsh
      - { role: paths, profile_file: ".zshenv" }
      - { role: python-root-packages, python_cmd: "python2", pip_bin: "/usr/bin/pip2" }
      - { role: python-root-packages, python_cmd: "python3", pip_bin: "/usr/bin/pip3" }
      - tmux-from-source
      - { role: python-user-packages, pip_bin: "/usr/bin/pip3", tags: run}
      - { role: datasets, fuel_data_path: "{{ansible_env.HOME}}/data" }
      - root
      - llvm
      - rpm-fusion-free-22
      - nvidia-driver
      - cuda-75
      - cuda-75-skel
      #- torch-cuda-75
      #- fb-torch-libs-cuda-75
      - { role: theano, device: cpu, theanorc_fn: ".theanoenv"}
      - { role: theano, device: gpu0, theanorc_fn: ".theanoenv0"}
      - { role: theano, device: gpu1, theanorc_fn: ".theanoenv1"}
      - { role: theano, device: gpu2, theanorc_fn: ".theanoenv2"}
      - { role: theano, device: gpu3, theanorc_fn: ".theanoenv3"}
      - pan
