- hosts: cake

  roles:
      - common
      - apt-basics
      - zsh
      - { role: paths, profile_file: ".zshenv" }
      - { role: python-root-packages, python_cmd: "python2", pip_bin: "/usr/bin/pip2", ipython_pkg: "ipython==5" }
      - { role: python-root-packages, python_cmd: "python3", pip_bin: "/usr/bin/pip3", ipython_pkg: "ipython" }
      #- tmux-from-source
      - { role: python-user-packages, pip_bin: "/usr/bin/pip3" }
      - root
