- hosts: cake

  roles:
      - common
      - dnf-basics
      - zsh
      - { role: paths, profile_file: ".zshenv" }
      - { role: python-root-packages, python_cmd: "python2", pip_bin: "/usr/bin/pip2" }
      - { role: python-root-packages, python_cmd: "python3", pip_bin: "/usr/bin/pip3" }
      - tmux-from-source
      - { role: python-user-packages, pip_bin: "/usr/bin/pip3" }
      - root
