- hosts: epfl

  vars:
    torch_source_cmd: ". $HOME/torch/install/bin/torch-activate"
    cuda_env:
      CUDA_ROOT: /usr/local/cuda
      CUDA_HOME: /usr/local/cuda
      CFLAGS: -I/usr/local/cuda/include 
      LDFLAGS: -L/usr/local/cuda/lib64 
      PATH: "/usr/local/cuda/bin:{{ ansible_env.PATH }}"
      LD_LIBRARY_PATH: "/usr/local/cuda/lib64:/usr/local/lib:{{ ansible_env.LD_LIBRARY_PATH | default('') }}"

  roles:
      - common
      - apt-basics
      - zsh
      - { role: paths, profile_file: ".zshenv" }
      - { role: python-root-packages, python_cmd: "python3", pip_bin: "/usr/bin/pip3" }
      - { role: python-user-packages, python_cmd: "python3", pip_bin: "/usr/bin/pip3" }
      - cudnn
      - tensorflow-from-source-epfl
