- hosts: gpus

  vars:
    torch_source_cmd: ". $HOME/torch/install/bin/torch-activate"
    cuda_env:
      CUDA_ROOT: /usr/local/cuda
      CUDA_HOME: /usr/local/cuda
      CFLAGS: -I/usr/local/cuda/include 
      LDFLAGS: -L/usr/local/cuda/lib64 
      PATH: "/usr/local/cuda/bin:{{ ansible_env.PATH }}"
      LD_LIBRARY_PATH: "/usr/local/cuda/lib64:/usr/local/lib:{{ ansible_env.LD_LIBRARY_PATH | default('') }}"

  roles:
      - common
      - dnf-basics
      - zsh
      - llvm
      - root
      - { role: paths, profile_file: ".zshenv" }
      - tmux-from-source
      - mathlibs
      - { role: hdf5-from-source, hdf5_version: "1.8.17" }
      - { role: python-root-packages, python_cmd: "python2", pip_bin: "/usr/bin/pip2" }
      - { role: python-root-packages, python_cmd: "python3", pip_bin: "/usr/bin/pip3" }
      - { role: python-user-packages, pip_bin: "/usr/bin/pip3", tags: run}
      - { role: datasets, fuel_data_path: "{{ansible_env.HOME}}/data" }
      - nvidia-driver
      - cuda-8
      - cuda-skel
      - torch-cuda
      - fb-torch-libs-cuda
      - fb-torch-rocks-cuda
      - tensorflow-from-source
      - opencv-from-source
