- hosts: gpus

  vars:
    torch_source_cmd: ". $HOME/torch/install/bin/torch-activate"
    cuda75_env:
      CUDA_ROOT: /usr/local/cuda-7.5
      CUDA_HOME: /usr/local/cuda-7.5
      CFLAGS: -I/usr/local/cuda-7.5/include 
      LDFLAGS: -L/usr/local/cuda-7.5/lib64 
      PATH: "/usr/local/cuda-7.5/bin:{{ ansible_env.PATH }}"
      LD_LIBRARY_PATH: "/usr/local/cuda-7.5/lib64:{{ ansible_env.LD_LIBRARY_PATH | default('') }}"

  roles:
      - common
      - dnf-basics
      - zsh
      - llvm
      - root
      - { role: paths, profile_file: ".zshenv" }
      - tmux-from-source
      - mathlibs
      - { role: hdf5-from-source, hdf5_version: "1.8.17" }
      - { role: python-root-packages, python_cmd: "python2", pip_bin: "/usr/bin/pip2" }
      - { role: python-root-packages, python_cmd: "python3", pip_bin: "/usr/bin/pip3" }
      - { role: python-user-packages, pip_bin: "/usr/bin/pip3", tags: run}
      #- { role: datasets, fuel_data_path: "{{ansible_env.HOME}}/data" }
      #- rpm-fusion-free-22
      - nvidia-driver
      - cuda-75
      - cuda-75-skel
      - torch-cuda-75
      - fb-torch-libs-cuda-75
      - fb-torch-rocks-cuda-75
      - { role: theano, device: cpu, theanorc_fn: ".theanoenv"}
      - { role: theano, device: gpu0, theanorc_fn: ".theanoenv0"}
      - { role: theano, device: gpu1, theanorc_fn: ".theanoenv1"}
      - { role: theano, device: gpu2, theanorc_fn: ".theanoenv2"}
      - { role: theano, device: gpu3, theanorc_fn: ".theanoenv3"}
