- hosts: all

  vars_prompt:
      - name: "username"
        prompt: "nethz-username"

  tasks:
      - shell: getent passwd | grep "^{{ username }}:"
        become: yes

      - shell: getent passwd | grep "^{{ username }}:" | cut -d ":" -f 3 
        register: lu_uid
        become: yes

      - shell: getent passwd | grep "^{{ username }}:" | cut -d ":" -f 4
        register: lu_gid
        become: yes

      - shell: getent passwd | grep "^{{ username }}:" | cut -d ":" -f 5
        register: lu_name
        become: yes

      - lineinfile: "dest=/etc/passwd line='{{ username }}:*:{{ lu_uid.stdout_lines[0] }}:{{ lu_gid.stdout_lines[0] }}:{{ lu_name.stdout_lines[0] }}:/local/home/{{ username }}:/bin/bash'"
        become: yes

      - lineinfile: "dest=/etc/shadow line='{{ username }}:*:16780:0:99999:7:::'"
        become: yes

      - lineinfile: "dest=/etc/group line='jbuhmann:x:{{ lu_gid.stdout_lines[0] }}:'"
        become: yes

      - file: path=/local/home/{{ username }} state=directory mode=0755 owner={{ username }} group=jbuhmann 
        register: homedir_result
        become: yes

      - shell: cp /etc/skel/{{ item }} /local/home/{{ username }}/{{ item }} && chown {{ username }}:jbuhmann /local/home/{{ username }}/{{ item }}
        become: yes
        when: homedir_result.changed
        with_items:
            - .bash_logout
            - .bash_profile
            - .bashrc
