- name: get pip install script
  shell: curl https://bootstrap.pypa.io/get-pip.py > get-pip.py creates=get-pip.py

- name: install pip3
  become: yes
  shell: python3 get-pip.py creates=/usr/bin/pip3

- name: upgrade pip3
  become: yes
  pip: name=pip executable=/usr/bin/pip3 extra_args="--upgrade"

- name: install python3 packages
  become: yes
  pip: name={{ item }} editable=no executable=/usr/bin/pip3 extra_args="--upgrade"
  with_items:
   - requests[security]
   - numpy
   - scipy
   - sklearn
   - matplotlib
   - Pillow
   - scikit-image
   - virtualenv
   - cython
