-   name: get pip install script
    shell: curl https://bootstrap.pypa.io/get-pip.py > get-pip.py creates=get-pip.py

-   name: install pip3
    become: yes
    shell: python3 get-pip.py creates=/usr/bin/pip3

-   name: install python3 packages
    become: yes
    pip: name={{ item }} executable=/usr/bin/pip3
    with_items:
        -   requests[security]
        -   numpy
        -   scipy
        -   sklearn
        -   matplotlib
        -   theano
        -   Pillow
        -   scikit-image
        -   virtualenv
        -   sacred
        -   cython
