- name: blacklist nouveau
  become: yes
  kernel_blacklist: name=nouveau state=present
  register: blnouveau

- include: ../../common/tasks/reboot.yml
  when: blnouveau.changed

- name: download nvidia driver installer
  get_url: url=http://us.download.nvidia.com/XFree86/Linux-x86_64/384.66/NVIDIA-Linux-x86_64-384.66.run dest={{ ansible_env.HOME }}/libsrc/nvidia.run mode=0544

- name: install nvidia driver
  become: yes
  command: "{{ ansible_env.HOME }}/libsrc/nvidia.run -s"
  args:
    creates: /usr/bin/nvidia-settings
  register: nvidiadriver

- include: ../../common/tasks/reboot.yml
  when: nvidiadriver.changed

- name: install nvidia-docker
  become: yes
  apt: deb=https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.1/nvidia-docker_1.0.1-1_amd64.deb state=present

