- name: install cython userspace 
  pip: name=Cython executable={{pip_bin}} extra_args="--user"

- name: install python userspace packages
  pip: name={{ item }} editable=no executable={{pip_bin}} extra_args="--user"
  with_items:
      - xxhash
      - "git+https://github.com/theano/theano"
      - "git+https://github.com/lasagne/lasagne"
      - "git+https://github.com/yk/fuel"
      - "git+https://github.com/yk/sacred"
      - "git+https://github.com/yk/nestedtotensor"
