- name: install cython userspace 
  pip: name=Cython executable={{pip_bin}} extra_args="--user"

- name: install python userspace packages
  pip: name={{ item }} editable=no executable={{pip_bin}} extra_args="--user"
  with_items:
      - sklearn
      - scikit-image
      - xxhash
      - nose
      - "git+https://github.com/theano/theano"
      - "git+https://github.com/lasagne/lasagne"
      #- "git+https://github.com/yk/fuel"
      - "git+https://github.com/WoLpH/python-progressbar"
      - "git+https://github.com/mila-udem/fuel"
      - "git+https://github.com/yk/sacred"
      - "git+https://github.com/yk/nestedtotensor"
      #- "git+https://github.com/yk/fast-jlt"
