-   hosts: gpu

    tasks:
        - name: make web dir
          file: path={{ansible_env.HOME}}/web state=directory
              
        - name: make web root dir
          file: path={{ansible_env.HOME}}/web/root state=directory

        - name: copy nginx conf
          copy: src=../files/nginx.conf dest={{ansible_env.HOME}}/web/nginx.conf

        - name: run server
          docker:
              name: local-web
              docker_api_version: auto
              image: nginx
              state: reloaded
              volumes:
                  - "{{ansible_env.HOME}}/web/root:/site:z"
                  - "{{ansible_env.HOME}}/web/nginx.conf:/etc/nginx/conf.d/example.conf:z"
              expose:
                  - 8080
              ports:
                  - "8080:8080"
