-   hosts: dco

    remote_user: root

    vars:
        -   username: ykilcher
        -   uid: 123937
        -   groupname: hofmann
        -   gid: 10275

    tasks:
        -   name: create user group
            group: name={{ groupname }} uid={{ gid }}

        -   name: create remote non-root user
            user: name={{ username }} uid={{ uid }} group={{ groupname }}

        -   name: set password
            shell: "date +%s | sha256sum | base64 | head -c 32 | passwd --stdin {{ username }}"

        -   name: add user to sudoers
            lineinfile: "dest=/etc/sudoers state=present regexp='^{{ username }}' line='{{ username }} ALL=(ALL) NOPASSWD: ALL'"

        -   name: add public key
            authorized_key: user={{ username }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}" path="/local/home/{{ username }}/.ssh/authorized_keys"
        #"


-   hosts: dco

    environment:
        PATH: "{{ ansible_env.PATH }}:~/bin"

    tasks:
        -   name: create bin dir
            file: path=~/bin state=directory mode=0755

        -   name: install yum packages
            become: yes
            yum: name=gcc-4.9.2,gcc-c++-4.9.2,gcc-gfortran-4.9.2,nano,freetype,freetype-devel,lapack,lapack-devel,blas,blas-devel,libffi,libffi-devel,libpng,libpng-devel,libtiff-devel,libjpeg-turbo-devel,libzip-devel,lcms2-devel,libwebp-devel,tcl-devel,tk-devel,openssl-devel,wget,curl,vim,python,python3,swig,zip,unzip,python-devel,python3-devel,git,java-1.8.0-openjdk-devel,zlib-devel,screen,openblas-devel,atlas-devel,protobuf-devel,leveldb-devel,snappy-devel,lmdb-devel,opencv-devel,boost-devel,hdf5-devel,gflags-devel,glog-devel,kernel-devel,kernel-headers,dkms,acpid,emacs,boost-devel,zsh,cmake state=present

        -   include: ../../common/tasks/python-defaults.yml
        -   include: ../../common/tasks/python3-defaults.yml

        -   name: install tensorflow python2
            become: yes
            pip: name=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl executable=/usr/bin/pip2

        -   name: install tensorflow python3
            become: yes
            pip: name=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp34-none-linux_x86_64.whl executable=/usr/bin/pip3
