-   hosts: dco-other-user

    remote_user: root

    vars_prompt:
        -   name: "username"
            prompt: "username"
        -   name: "password"
            prompt: "password"

    tasks:
        -   name: create remote non-root user
            user: name={{ username }}

        -   name: set password
            shell: echo {{ password }} | passwd --stdin {{ username }}

        -   name: add user to sudoers
            lineinfile: "dest=/etc/sudoers state=present regexp='^{{ username }}' line='{{ username }} ALL=(ALL) NOPASSWD: ALL'"
