- hosts: dco

  remote_user: root

  vars:
    - username: ykilcher
    - uid: 123937
    - groupname: hofmann
    - gid: 10275

  tasks:
    - name: create user group
      group: name={{ groupname }} gid={{ gid }}

    - name: create remote non-root user
      user: name={{ username }} uid={{ uid }} group={{ groupname }} home=/local/home/{{ username }}
      register: createuser

    - name: set password
      shell: "date +%s | sha256sum | base64 | head -c 32 | passwd --stdin {{ username }}"
      when: createuser.changed

    - name: add user to sudoers
      lineinfile: "dest=/etc/sudoers state=present regexp='^{{ username }}' line='{{ username }} ALL=(ALL) NOPASSWD: ALL'"

    - name: add public key
      authorized_key: user={{ username }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}" path="/local/home/{{ username }}/.ssh/authorized_keys"
    #
    - name: install zsh
      dnf: name=zsh state=present

    - name: make zsh default shell
      user: name={{ username }} shell=/usr/bin/zsh



- hosts: dco

  environment:
    PATH: "{{ ansible_env.PATH }}:~/bin"

  tasks:
    - name: create bin dir
      file: path=~/bin state=directory mode=0755

    - name: install dnf packages
      become: yes
      dnf: name=gcc,gcc-c++,gcc-gfortran,nano,freetype,freetype-devel,lapack,lapack-devel,blas,blas-devel,libffi,libffi-devel,libpng,libpng-devel,libtiff-devel,libjpeg-turbo-devel,libzip-devel,lcms2-devel,libwebp-devel,tcl-devel,tk-devel,openssl-devel,wget,curl,vim,python,python3,swig,zip,unzip,python-devel,python-tools,python3-devel,git,java-1.8.0-openjdk-devel,zlib-devel,screen,openblas-devel,atlas-devel,protobuf-devel,leveldb-devel,snappy-devel,lmdb-devel,opencv-devel,boost-devel,hdf5-devel,gflags-devel,glog-devel,kernel-devel,kernel-headers,dkms,acpid,emacs,boost-devel,zsh,cmake,htop,python-ipython,python3-ipython,pcre,graphviz,ctags,autojump,autojump-zsh,libevent,libevent-devel,readline-devel,ncurses-devel,gnuplot,nodejs,npm,ImageMagick,GraphicsMagick-devel,fftw-devel,sox-devel,sox,qt-devel,qtwebkit-devel,czmq,czmq-devel,automake,autoconf,autoconf-archive,libtool,double-conversion-devel,libtool,lz4-devel,lzma-devel,snappy-devel,numactl-libs,numactl-devel,flex,flex-devel,bison,bison-devel,libatomic,cyrus-sasl,cyrus-sasl-devel,libedit,libedit-devel,matio,matio-devel,cowsay,sl,mosh,docker,unzip state=present

    - include: ../../common/tasks/python-defaults.yml
    - include: ../../common/tasks/python3-defaults.yml

    - include: ../../common/tasks/tmux_from_source.yml
    - include: ../../common/tasks/install_tmux.yml

