-   name: ignore tarball
    connection: local
    lineinfile: "dest={{lookup('env', 'HOME')}}/git/dotfiles/.gitignore line='dotfiles.tar.gz'"

-   name: create tarball
    connection: local
    shell: "cd {{lookup('env', 'HOME')}}/git/dotfiles && tar czf dotfiles.tar.gz .zshrc .oh-my-zsh .vimrc .vim .tmux.conf"

-   name: delete vim folder
    file: "path={{lookup('env', 'HOME')}}/.vim state=absent"

-   name: copy and unpack tarball
    unarchive: "src={{lookup('env', 'HOME')}}/git/dotfiles/dotfiles.tar.gz dest={{ ansible_env.HOME }} extra_opts='--overwrite'"
