- name: install dnf packages
  become: yes
  dnf: name=lvm2,lvm2-libs state=present

- name: reboot
  become: yes
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for boot
  local_action: wait_for host={{ inventory_hostname }} state=started port=22 timeout=300 delay=15
