-   hosts: gpu
    
    vars_prompt:
        -   name: "username"
            prompt: "nethz-username"
        -   name: "group"
            prompt: "group"
        -   name: "password"
            prompt: "password"

    tasks:
        -   user: name={{ username }} group={{ group }} home=/local/home/{{ username }} skeleton=/etc/skel
            sudo: yes
