-   hosts: gpu

    tasks:
        -   name: clone repository
            git: repo=https://github.com/tensorflow/tensorflow dest={{ ansible_env.HOME }}/tensorflow 

        -   name: configure tensorflow
            shell: cd {{ ansible_env.HOME }}/tensorflow && PYTHON_BIN_PATH=/usr/bin/python3 TF_NEED_CUDA=1 CUDA_TOOLKIT_PATH=/usr/local/cuda CUDNN_INSTALL_PATH=/usr/local/cuda ./configure creates={{ ansible_env.HOME }}/tensorflow/tools/python_bin_path.sh

          #-   name: correct 2to3 file
          #lineinfile: dest={{ ansible_env.HOME }}/tensorflow/bazel-out/host/bin/external/bazel_tools/tools/python/2to3 line='exit 1' state=absent

          #-   name: correct 2to3 file part 2
          #lineinfile: dest={{ ansible_env.HOME }}/tensorflow/bazel-out/host/bin/external/bazel_tools/tools/python/2to3 line='exec 2to3 $@' state=present

          #-   name: modify mtime of 2to3
          #shell: cd {{ ansible_env.HOME }}/tensorflow/bazel-out/host/bin/external/bazel_tools/tools/python && touch -h -mt 2001010101 ./2to3 && touch dummy creates={{ ansible_env.HOME }}/tensorflow/bazel-out/host/bin/external/bazel_tools/tools/python/dummy


        -   name: build pip package
            shell: cd {{ ansible_env.HOME }}/tensorflow && bazel build -c opt --config=cuda --genrule_strategy=standalone --spawn_strategy=standalone //tensorflow/tools/pip_package:build_pip_package && bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg #creates=/tmp/tensorflow_pkg/tensorflow-0.6.0-py3-none-any.whl

        -   name: install pip package
            pip: executable=pip3 extra_args='--user --upgrade' name='file:///tmp/tensorflow_pkg/tensorflow-0.6.0-py3-none-any.whl'
