-   hosts: gpu

    tasks:
        -   name: modify path to contain cuda stuff
            lineinfile: dest={{ ansible_env.HOME }}/.bashrc line='export PATH="/usr/local/cuda/bin:$PATH"'

        -   name: modify library path to contain cuda stuff
            lineinfile: dest={{ ansible_env.HOME }}/.bashrc line='export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"'

        -   name: add cuda include dir to bashrc
            lineinfile: dest={{ ansible_env.HOME }}/.bashrc line='export CUDA_ROOT="/usr/local/cuda"'

        -   name: add cuda include dir to bashrc
            lineinfile: dest={{ ansible_env.HOME }}/.bashrc line='export CUDA_HOME="/usr/local/cuda"'
