- name: clone folly repository
  git: repo=https://github.com/facebook/folly.git dest={{ ansible_env.HOME }}/libsrc/folly update=no

#- name: change folly build
  #lineinfile: "dest={{ ansible_env.HOME }}/libsrc/folly/folly/m4/ax_boost_context.m4 regexp='fcontext_t' line='                [[boost::context::fcontext_t fc = boost::context::make_fcontext(0, 0, 0);]])],'"

- name: build folly
  shell: cd libsrc/folly/folly && autoreconf -ivf && ./configure && make -j14 creates={{ ansible_env.HOME }}/libsrc/folly/folly/.libs/libfolly.so
  register: buildfolly_result

- name: install folly
  become: yes
  shell: cd libsrc/folly/folly && make install && ldconfig
  when: buildfolly_result.changed

- name: clone wangle repository
  git: repo=https://github.com/facebook/wangle.git dest={{ ansible_env.HOME }}/libsrc/wangle update=no

- name: build wangle
  shell: cd libsrc/wangle/wangle && cmake . && make -j14 creates={{ ansible_env.HOME }}/libsrc/wangle/wangle/lib/libwangle.a
  register: buildwangle_result

- name: install wangle
  become: yes
  shell: cd libsrc/wangle/wangle && make install
  when: buildwangle_result.changed

- name: clone mstch repository
  git: repo=https://github.com/no1msd/mstch.git dest={{ ansible_env.HOME }}/libsrc/mstch update=no

- name: build mstch
  shell: cd libsrc/mstch && mkdir -p build && cd build && cmake .. && make -j14 creates={{ ansible_env.HOME }}/libsrc/mstch/build/src/libmstch.a
  register: buildmstch_result

- name: install mstch
  become: yes
  shell: cd libsrc/mstch/build && make install
  when: buildmstch_result.changed

- name: clone zstd repository
  git: repo=https://github.com/facebook/zstd.git dest={{ ansible_env.HOME }}/libsrc/zstd update=no

- name: build zstd
  shell: cd libsrc/zstd && make -j14 creates={{ ansible_env.HOME }}/libsrc/zstd/lib/libzstd.a
  register: buildzstd_result

- name: install zstd
  become: yes
  shell: cd libsrc/zstd && make install && ldconfig
  when: buildzstd_result.changed


- name: clone fbthrift repository
  git: repo=https://github.com/facebook/fbthrift.git dest={{ ansible_env.HOME }}/libsrc/fbthrift update=no 

- name: build fbthrift
  shell: cd libsrc/fbthrift/thrift && autoreconf -ivf && ./configure && make -j14 creates={{ ansible_env.HOME }}/libsrc/fbthrift/thrift/lib/cpp2/.libs/libthriftcpp2.so
  register: buildfbthrift_result

- name: install fbthrift
  become: yes
  shell: "cd libsrc/fbthrift/thrift && make install && chown -R {{ansible_env.USER}}: {{ansible_env.HOME}}/libsrc/fbthrift/thrift && ldconfig"
  when: buildfbthrift_result.changed


- name: install ansible2
  become: yes
  pip: name=ansible executable=/usr/bin/pip2

- name: clone nccl
  git: repo=https://github.com/NVIDIA/nccl.git dest={{ ansible_env.HOME }}/libsrc/nccl update=no

- name: build nccl
  shell: cd libsrc/nccl && make -j14 creates={{ ansible_env.HOME }}/libsrc/nccl/build/lib/libnccl.so
  environment: "{{ cuda_env }}"
  register: buildnccl_result

- name: install nccl
  become: yes
  shell: cd libsrc/nccl && make install
  environment: "{{ cuda_env }}"
  when: buildnccl_result.changed
