- name: download hdf5 source
  get_url: url=http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-{{hdf5_version}}.tar.gz dest={{ansible_env.HOME}}/libsrc/hdf5.tar.gz

- name: untar hdf5
  unarchive: src={{ansible_env.HOME}}/libsrc/hdf5.tar.gz copy=no dest={{ansible_env.HOME}}/libsrc creates={{ansible_env.HOME}}/libsrc/hdf5-{{hdf5_version}}/configure

- name: build hdf5
  shell: cd libsrc/hdf5-{{hdf5_version}} ; ./configure --prefix={{ansible_env.HOME}}/ext && make creates={{ansible_env.HOME}}/libsrc/hdf5-{{hdf5_version}}/libtool
  register: buildhdf5result

- name: build and install hdf5
  shell: cd libsrc/hdf5-{{hdf5_version}} ; make install 
  when: buildhdf5result.changed

- name: add hdf5 env variable
  lineinfile: dest={{ ansible_env.HOME }}/{{ item }} create=yes line='export HDF5_DIR={{ansible_env.HOME}}/ext'
  with_items:
      - .profile
      - .zshenv
