- name: get pip install script
  get_url: url='https://bootstrap.pypa.io/get-pip.py' dest={{ansible_env.HOME}}/libsrc/get-pip.py

- name: install pip
  become: yes
  shell: "{{python_cmd}} libsrc/get-pip.py creates={{pip_bin}}"

#- name: upgrade pip
  #become: yes
  #pip: name=pip executable={{pip_bin}} extra_args="--upgrade"

#- name: install cython
  #become: yes
  #pip: name=cython editable=no executable={{pip_bin}} extra_args="--upgrade"

- name: install python packages
  become: yes
  pip: name={{ item }} editable=no executable={{pip_bin}} extra_args="--upgrade"
  environment:
      LD_LIBRARY_PATH: "/usr/lib"
  with_items:
   - requests[security]
   - virtualenv
   #- 'https://github.com/numpy/numpy/archive/v1.11.1.tar.gz'
   #- 'https://github.com/scipy/scipy/archive/v0.17.1.tar.gz'
   - numpy
   - scipy
   - "{{ipython_pkg}}"
   - matplotlib
   - Pillow
