- name: get pip install script
  shell: curl https://bootstrap.pypa.io/get-pip.py > libsrc/get-pip.py creates=libsrc/get-pip.py

- name: install pip3
  become: yes
  shell: "{{python_cmd}} libsrc/get-pip.py creates={{pip_bin}}"

- name: upgrade pip
  become: yes
  pip: name=pip executable={{pip_bin}} extra_args="--upgrade"

- name: install python packages
  become: yes
  pip: name={{ item }} editable=no executable={{pip_bin}} extra_args="--upgrade"
  with_items:
   - requests[security]
   - numpy
   - scipy
   - sklearn
   - matplotlib
   - Pillow
   - scikit-image
   - virtualenv
